### PR TITLE
Max speed cvar + optimization

### PR DESCRIPTION
**Pull request by thecraftianman**
- Changed hook names to clearly show what mod they're from
- Notable optimization throughout the whole mod (especially while not actively sliding)
- Added a cvar to control max speed (sliding_ability_max_speed) to prevent the ability being used as an easy bhop by default
- Clamped all cvars to a minimum value of 0

### CODE REVIEW

**Comment by ZenkakuHiragana** [comment]
Thank you so much for all the changes!
But the default value of sliding_ability_max_speed will be larger (I think around 2500 is good) as many people are enjoying the bunny hop feature.

**Comment by thecraftianman** [comment]
No issues with the higher max speed! Any particular reason why you reverted the changes to the crouching check, though? From my benchmarking, that significantly improved the performance of the addon when people aren't actively sliding, and nothing actually happens to the player when they aren't crouching as-is. I'm happy to run some numbers for you if you haven't done so yourself.

**Comment by ZenkakuHiragana** [comment]
The changes around crouching check caused an issue relating to lag compensation; it feels pretty laggy while bunny hopping.  I was testing it with a dedicated server and a fake lag with net_fakelag 200.  I'm not sure why, but reverting the changes fixed it.

**Comment by ZenkakuHiragana** [comment]
Also, I made changes around networking bone manipulation because other players couldn't see the sliding posture with this commit.  The latest one fixes it and still have less network usage.

**Comment by thecraftianman** [comment]
I'm comparing the crouching check changes to the current Workshop build right now on my own dedicated server with net_fakelag 200, but I'm finding that the same lag feeling exists in both versions during a ping spike. Unless I'm overlooking something, I'm fairly certain that the root issue lies somewhere else in the code.

The bone manipulation change looks perfectly fine, though.

**Comment by ZenkakuHiragana** [comment]
Hmm, that's strange.  Additional information to note here is that when I was testing, there was a plenty of time between changing the fake lag and testing the feeling.  The ping increases over time after net_fakelag 200 and I think many behavior becomes unstable until the player has a stable ping. 

Maybe I have to do more tests, but I can't do it right now.

**Pull request merged**
